[build]
  base = "job-portal/frontend"
  command = "npm install && npm run build"
  publish = "job-portal/frontend/dist"

[dev]
  command = "npm run dev"
  port = 3000

[build.environment]
  NODE_VERSION = "16"  # Optional: Specify Node.js version if needed
